INSERT INTO `xt_tohop_monthi` (`matohop`, `mon1`, `mon2`, `mon3`, `tentohop`) VALUES
('A00','TO','LI','HO','Toán Lý Hóa'),
('A01','TO','LI','N1','Toán Lý Tiếng Anh'),
('A02','TO','LI','SI','Toán Lý Sinh'),
('A03','TO','LI','SU','Toán Lý Sử'),
('A04','TO','LI','DI','Toán Lý Địa'),
('A05','TO','HO','SU','Toán Hóa Sử'),
('A06','TO','HO','DI','Toán Hóa Địa'),
('A07','TO','SU','DI','Toán Sử Địa'),
('B00','TO','HO','SI','Toán Hóa Sinh'),
('B01','TO','SI','SU','Toán Sinh Sử'),
('B02','TO','SI','DI','Toán Sinh Địa'),
('B03','TO','VA','SI','Toán Văn Sinh'),
('B08','TO','SI','N1','Toán Sinh Tiếng Anh'),
('C00','VA','SU','DI','Văn Sử Địa'),
('C01','TO','VA','LI','Toán Văn Lý'),
('C02','TO','VA','HO','Toán Văn Hóa'),
('C03','TO','VA','SU','Toán Văn Sử'),
('C04','TO','VA','DI','Toán Văn Địa'),
('C05','VA','LI','HO','Văn Lý Hóa'),
('C06','VA','LI','SI','Văn Lý Sinh'),
('C07','VA','LI','SU','Văn Lý Sử'),
('C08','VA','HO','SI','Văn Hóa Sinh'),
('C09','VA','LI','DI','Văn Lý Địa'),
('C10','VA','HO','SU','Văn Hóa Sử'),
('C11','VA','HO','DI','Văn Hóa Địa'),
('C12','VA','SI','SU','Văn Sinh Sử'),
('C13','VA','SI','DI','Văn Sinh Địa'),
('D01','TO','VA','N1','Toán Văn Tiếng Anh'),
('D07','TO','HO','N1','Toán Hóa Tiếng Anh'),
('D09','TO','SU','N1','Toán Sử Tiếng Anh'),
('D10','TO','DI','N1','Toán Địa Tiếng Anh'),
('D11','VA','LI','N1','Văn Lý Tiếng Anh'),
('D12','VA','HO','N1','Văn Hóa Tiếng Anh'),
('D13','VA','SI','N1','Văn Sinh Tiếng Anh'),
('D14','VA','SU','N1','Văn Sử Tiếng Anh'),
('D15','VA','DI','N1','Văn Địa Tiếng Anh'),
('H00','VA','NK3','NK4','Văn Năng khiếu 3 Năng khiếu 4'),
('M01','NK1','NK2','VA','Năng khiếu 1 Năng khiếu 2 Văn'),
('M02','NK1','TO','NK2','Năng khiếu 1 Toán Năng khiếu 2'),
('N01','VA','NK5','NK6','Văn Năng khiếu 5 Năng khiếu 6'),
('X01','TO','VA','KTPL','Toán Văn Kinh tế và pháp luật'),
('X02','TO','VA','TI','Toán Văn Tin học'),
('X03','TO','VA','CNCN','Toán Văn Công nghệ công nghiệp'),
('X04','TO','VA','CNNN','Toán Văn Công nghệ nông nghiệp'),
('X05','TO','LI','KTPL','Toán Lý Kinh tế và pháp luật'),
('X06','TO','LI','TI','Toán Lý Tin học'),
('X07','TO','LI','CNCN','Toán Lý Công nghệ công nghiệp'),
('X08','TO','LI','CNNN','Toán Lý Công nghệ nông nghiệp'),
('X09','TO','HO','KTPL','Toán Hóa Kinh tế và pháp luật'),
('X10','TO','HO','TI','Toán Hóa Tin học'),
('X11','TO','HO','CNCN','Toán Hóa Công nghệ công nghiệp'),
('X12','TO','HO','CNNN','Toán Hóa Công nghệ nông nghiệp'),
('X13','TO','SI','KTPL','Toán Sinh Kinh tế và pháp luật'),
('X14','TO','SI','TI','Toán Sinh Tin học'),
('X15','TO','SI','CNCN','Toán Sinh Công nghệ công nghiệp'),
('X16','TO','SI','CNNN','Toán Sinh Công nghệ nông nghiệp'),
('X17','TO','SU','KTPL','Toán Sử Kinh tế và pháp luật'),
('X18','TO','SU','TI','Toán Sử Tin học'),
('X19','TO','SU','CNCN','Toán Sử Công nghệ công nghiệp'),
('X20','TO','SU','CNNN','Toán Sử Công nghệ nông nghiệp'),
('X21','TO','DI','KTPL','Toán Địa Kinh tế và pháp luật'),
('X22','TO','DI','TI','Toán Địa Tin học'),
('X23','TO','DI','CNCN','Toán Địa Công nghệ công nghiệp'),
('X24','TO','DI','CNNN','Toán Địa Công nghệ nông nghiệp'),
('X25','TO','N1','KTPL','Toán Tiếng Anh Kinh tế và pháp luật'),
('X26','TO','N1','TI','Toán Tiếng Anh Tin học'),
('X27','TO','N1','CNCN','Toán Tiếng Anh Công nghệ công nghiệp'),
('X28','TO','N1','CNNN','Toán Tiếng Anh Công nghệ nông nghiệp'),
('X53','TO','KTPL','TI','Toán Kinh tế và pháp luật Tin học'),
('X54','TO','KTPL','CNCN','Toán Kinh tế và pháp luật Công nghệ công nghiệp'),
('X55','TO','KTPL','CNNN','Toán Kinh tế và pháp luật Công nghệ nông nghiệp'),
('X56','TO','TI','CNCN','Toán Tin học Công nghệ công nghiệp'),
('X57','TO','TI','CNNN','Toán Tin học Công nghệ nông nghiệp'),
('X58','VA','LI','KTPL','Văn Lý Kinh tế và pháp luật'),
('X59','VA','LI','TI','Văn Lý Tin học'),
('X60','VA','LI','CNCN','Văn Lý Công nghệ công nghiệp'),
('X61','VA','LI','CNNN','Văn Lý Công nghệ nông nghiệp'),
('X62','VA','HO','KTPL','Văn Hóa Kinh tế và pháp luật'),
('X63','VA','HO','TI','Văn Hóa Tin học'),
('X64','VA','HO','CNCN','Văn Hóa Công nghệ công nghiệp'),
('X65','VA','HO','CNNN','Văn Hóa Công nghệ nông nghiệp'),
('X66','VA','SI','KTPL','Văn Sinh Kinh tế và pháp luật'),
('X67','VA','SI','TI','Văn Sinh Tin học'),
('X68','VA','SI','CNCN','Văn Sinh Công nghệ công nghiệp'),
('X69','VA','SI','CNNN','Văn Sinh Công nghệ nông nghiệp'),
('X70','VA','SU','KTPL','Văn Sử Kinh tế và pháp luật'),
('X71','VA','SU','TI','Văn Sử Tin học'),
('X72','VA','SU','CNCN','Văn Sử Công nghệ công nghiệp'),
('X73','VA','SU','CNNN','Văn Sử Công nghệ nông nghiệp'),
('X74','VA','DI','KTPL','Văn Địa Kinh tế và pháp luật'),
('X75','VA','DI','TI','Văn Địa Tin học'),
('X76','VA','DI','CNCN','Văn Địa Công nghệ công nghiệp'),
('X77','VA','DI','CNNN','Văn Địa Công nghệ nông nghiệp'),
('X78','VA','N1','KTPL','Văn Tiếng Anh Kinh tế và pháp luật'),
('X79','VA','N1','TI','Văn Tiếng Anh Tin học'),
('X80','VA','N1','CNCN','Văn Tiếng Anh Công nghệ công nghiệp'),
('X81','VA','N1','CNNN','Văn Tiếng Anh Công nghệ nông nghiệp'),
('Y07','VA','KTPL','TI','Văn Kinh tế và pháp luật Tin học'),
('Y08','VA','KTPL','CNCN','Văn Kinh tế và pháp luật Công nghệ công nghiệp'),
('Y09','VA','KTPL','CNNN','Văn Kinh tế và pháp luật Công nghệ nông nghiệp'),
('Y10','VA','TI','CNCN','Văn Tin học Công nghệ công nghiệp'),
('Y11','VA','TI','CNNN','Văn Tin học Công nghệ nông nghiệp');
/*!40000 ALTER TABLE `xt_tohop_monthi` ENABLE KEYS */;
UNLOCK TABLES;
